name: Create Pre-release

on:
  release:
    types: [published]

jobs:
  create-prerelease:
    if: |
      !contains(github.event.release.tag_name, '-pre') &&
      github.repository != 'remla25-team8/operation'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Calculate next pre-release version
        id: version
        run: |
          # Extract base version (v1.2.3 -> 1.2.3)
          BASE_VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          
          # Split into major.minor.patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "$BASE_VERSION"
          
          # Increment PATCH version (1.2.3 -> 1.2.4-pre)
          NEXT_PATCH=$((PATCH + 1))
          NEXT_VERSION="v${MAJOR}.${MINOR}.${NEXT_PATCH}-pre"
          STABLE_VERSION="v${MAJOR}.${MINOR}.${NEXT_PATCH}"
          
          echo "next_version=${NEXT_VERSION}" >> $GITHUB_OUTPUT
          echo "stable_version=${STABLE_VERSION}" >> $GITHUB_OUTPUT
          echo "Created pre-release version: ${NEXT_VERSION}"

      - name: Create pre-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.next_version }}
          name: "Pre-release ${{ steps.version.outputs.next_version }}"
          body: |
            Automated pre-release for testing.
            
            **Parent Release**: ${{ github.event.release.tag_name }}
            
            This pre-release will become ${{ steps.version.outputs.stable_version }} when stable.
          prerelease: true
          draft: false

      - name: Update main branch version
        if: github.ref == 'refs/heads/main'
        run: |
          # Update version file (e.g., version.txt or pyproject.toml)
          echo "${{ steps.version.outputs.next_version }}" > version.txt
          
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add version.txt
          git commit -m "Bump version to ${{ steps.version.outputs.next_version }} [skip ci]"
          git push origin main